import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TopBar from '@/components/TopBar'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import { Provider } from 'react-redux'
import { store } from '@/redux/store'
import { MyProvider } from '@/context/MyContext'
import Layout from '@/components/Layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
  <Layout>
        <TopBar/>
        <NavBar/>
        {children}
        <Footer/>
  </Layout>
        </body>
      
    </html>
  )
}
